apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-minio-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-minio
  template:
    metadata:
      labels:
        app: python-minio
    spec:
      containers:
        - name: python-minio-container
          image: auroraharbor.smartstream-stp.com/bmtest/minio-python:0.4
          ports:
            - containerPort: 5000
---

apiVersion: v1
kind: Service
metadata:
  name: python-minio-service
spec:
  selector:
    app: python-minio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: minio-python-route
spec:
  host: minio-python-route-minio-python.apps.okd4.smartstream-stp.com
  port:
    targetPort: 5000
  to:
    kind: Service
    name: python-minio-service
    weight: 100
  wildcardPolicy: None
